// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	services "github.com/reco/pkg/services"
	mock "github.com/stretchr/testify/mock"
)

// BaseUsersServiceInterface is an autogenerated mock type for the BaseUsersServiceInterface type
type BaseUsersServiceInterface struct {
	mock.Mock
}

// Store provides a mock function with given fields: user
func (_m *BaseUsersServiceInterface) Store(user services.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(services.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBaseUsersServiceInterface creates a new instance of BaseUsersServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBaseUsersServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BaseUsersServiceInterface {
	mock := &BaseUsersServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
