// Code generated by mockery v2.50.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// BaseClientInterface is an autogenerated mock type for the BaseClientInterface type
type BaseClientInterface struct {
	mock.Mock
}

// Get provides a mock function with given fields: path, query
func (_m *BaseClientInterface) Get(path string, query map[string]string) (*http.Response, error) {
	ret := _m.Called(path, query)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(string, map[string]string) (*http.Response, error)); ok {
		return rf(path, query)
	}
	if rf, ok := ret.Get(0).(func(string, map[string]string) *http.Response); ok {
		r0 = rf(path, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(string, map[string]string) error); ok {
		r1 = rf(path, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBaseClientInterface creates a new instance of BaseClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBaseClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *BaseClientInterface {
	mock := &BaseClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
